ManifestType: installer
ManifestVersion: 1.6.0
PackageIdentifier: Google.IAPDesktop
PackageVersion: '2.42.1564'

Platform:
- Windows.Desktop
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-08-13T00:04:51Z
AppsAndFeaturesEntries:
- UpgradeCode: '{8077382C-6B47-11EA-BC55-0242AC130003}'
Installers:
- Architecture: x64
  ProductCode: '{E278F76B-9DB0-489D-AA09-A2019D87683F}'
  InstallerUrl: https://github.com/GoogleCloudPlatform/iap-desktop/releases/download/2.42.1561/IapDesktopX64.msi
  InstallerSha256: F6153C08C3E44B43E45741327F500CEE14372976B5770171E58DD0D9758595BB
- Architecture: x86
  ProductCode: '{9D55EB76-0639-4BDF-8B22-C9B67AE97979}'
  InstallerUrl: https://github.com/GoogleCloudPlatform/iap-desktop/releases/download/2.42.1561/IapDesktopX86.msi
  InstallerSha256: B7694A2F81C83B79A0980B265D51B759156CEB864C663076FD88EE3581EAD25E
